name: Common Checks
on:
  push:
    # Do not run on branches for Dev and Prod to avoid duplicated workflow runs
    branches-ignore:
      - master
      - develop

jobs:
  run-test:
    uses: ./.github/workflows/run-tests-reusable.yaml

  run-lint:
    uses: ./.github/workflows/run-linting-reusable.yaml
