name: Deploy PROD On Push workflow

on:
  push:
    branches:
      - master

jobs:
  run-test:
    uses: ./.github/workflows/run-tests-reusable.yaml

  run-lint:
    uses: ./.github/workflows/run-linting-reusable.yaml

  # Requires test and lint be completed
  this-is-like-prod-deploy:

    runs-on: ubuntu-latest
    needs: [run-test,run-lint]

    steps:

    - name: Mock PROD deploy
      run: echo "Hello PROD"
