name: Deploy DEV On Push workflow

on:
  push:
    branches:
      - develop
jobs:
  run-test:
    uses: ./.github/workflows/run-tests-reusable.yaml

  run-lint:
    uses: ./.github/workflows/run-linting-reusable.yaml

  # Not requiring successful dependent jobs
  this-is-like-dev-deploy:

    runs-on: ubuntu-latest
    needs: [run-test,run-lint]
    # Run even if test and lint fail, but job still can be cancelled
    if: success() || failure()

    steps:
    - name: Mock DEV deploy
      run: echo "Hello DEV"
