name: On Manual Dispatch

on:
  workflow_dispatch:

jobs:
  run-test:
    uses: ./.github/workflows/run-tests-reusable.yaml

  run-lint:
    uses: ./.github/workflows/run-linting-reusable.yaml

  # Not requiring successful dependent jobs
  this-is-like-dev-deploy:

    name: Fake DEV Deploy
    runs-on: ubuntu-latest
    needs: [run-test,run-lint]

    steps:
    - name: Mock DEV deploy
      run: echo "Hello DEV"

    - name: Fail!
      run: exit 1


  # Deploy on Prod only if Dev Deployment succesful
  this-is-like-prod-deploy:

    name: Fake PROD Deploy
    runs-on: ubuntu-latest
    # Requires test and lint be completed
    needs: [run-test,run-lint,this-is-like-dev-deploy]

    steps:

    - name: Mock PROD deploy
      run: echo "Hello PROD"

